name: selfsync
description: "A mood tracking Flutter application with clean, modern UI"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  fl_chart: ^0.69.0
  flutter_dotenv: ^5.2.1
  
  # Cloud Backup dependencies
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.6.2
  firebase_storage: ^12.3.5
  
  image_picker: ^1.0.7
  image_cropper: ^8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo.png
    - assets/icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"